# Generated by Django 3.1.7 on 2021-05-31 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='created',
            field=models.DateField(default='2021-05-31'),
        ),
        migrations.AddField(
            model_name='todo',
            name='due_date',
            field=models.DateField(default='2021-05-31'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='todo',
            order_with_respect_to='user',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='date',
        ),
    ]
