# Generated by Django 3.1.7 on 2021-05-31 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210531_0722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name': 'user', 'verbose_name_plural': 'uses'},
        ),
        migrations.AlterModelTable(
            name='todo',
            table='TODO',
        ),
        migrations.AlterOrderWithRespectTo(
            name='todo',
            order_with_respect_to=None,
        ),
    ]
