# Generated by Django 3.1.7 on 2021-05-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20210531_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[(1, 'Completed'), (0, 'Pending')], max_length=20),
        ),
    ]
