# Generated by Django 3.1.7 on 2021-05-31 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20210531_0815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='due_date',
            new_name='Deadline',
        ),
    ]
