# Generated by Django 3.1.7 on 2021-05-31 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20210531_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='Deadline',
            field=models.DateField(default='31-05-2021'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created',
            field=models.DateField(default='31-05-2021'),
        ),
    ]
