# Generated by Django 3.1.7 on 2021-05-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_auto_20210531_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='Deadline',
            field=models.DateField(default='2021-05-31'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created',
            field=models.DateField(default='2021-05-31'),
        ),
    ]
