# Generated by Django 3.1.7 on 2021-06-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_auto_20210531_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='Deadline',
            field=models.DateField(default='2021-06-01'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created',
            field=models.DateField(default='2021-06-01'),
        ),
    ]
